version: '3.8'

services:
  # The Database Service
  db:
    image: postgres:15-alpine
    container_name: library-db1
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: library_service
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The NestJS API Service
  api:
    build: .
    container_name: library_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db   # This matches the service name above
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: password123
      DB_NAME: library_service
    depends_on:
      - db

volumes:
  postgres_data: